import { readFileSync, writeFileSync } from "fs";

const PUNS = {
  "afghanistan":                        "Afghani-baa-n",
  "albania":                            "Albaa-nia",
  "algeria":                            "Alge-baa-ria",
  "angola":                             "An-wool-a",
  "antigua-and-barbuda":                "Antigua and Baa-buda",
  "argentina":                          "Argen-fleece-a",
  "armenia":                            "Arme-baa-nia",
  "australia":                          "Aus-SHEAR-lia",
  "austria":                            "Austri-ewe",
  "azerbaijan":                         "Azerbai-baa-n",
  "bahamas":                            "Baa-hamas",
  "bahrain":                            "Baa-rain",
  "bangladesh":                         "Baa-ngladesh",
  "barbados":                           "Baa-rbados",
  "belarus":                            "Bela-fleece",
  "belgium":                            "Belgi-ewe-m",
  "belize":                             "Be-fleece!",
  "benin":                              "Be-baa-nin",
  "bhutan":                             "Baa-tan",
  "bolivia-plurinational-state-of":     "Boli-baa-ia",
  "bosnia-and-herzegovina":             "Bos-baa-nia",
  "botswana":                           "Bots-wool-na",
  "brazil":                             "Baa-zil",
  "brunei-darussalam":                  "Bru-baa-i",
  "bulgaria":                           "Bulga-baa-ia",
  "burkina-faso":                       "Burki-baa Faso",
  "burundi":                            "Baa-rundi",
  "cabo-verde":                         "Cabo Ewe-rde",
  "cameroon":                           "Came-baa-oon",
  "canada":                             "Cana-baa",
  "central-african-republic":           "Central Wool-rican Rep.",
  "chad":                               "Baa-d Chad",
  "chile":                              "Chilly fleece",
  "china":                              "Chin-baa",
  "china-hong-kong-sar":                "Hong Baa-ng",
  "china-mainland":                     "Main-baa-nd",
  "colombia":                           "Colom-baa",
  "comoros":                            "Comoroos!",
  "congo":                              "Con-wool-go",
  "costa-rica":                         "Costa Ewe-ca",
  "cote-d-ivoire":                      "Côte d'Ewe-voire",
  "croatia":                            "Croa-baa-tia",
  "cuba":                               "Ewe-ba",
  "cyprus":                             "Cy-fleece",
  "czechia":                            "Czech-ewe-out",
  "czechoslovakia":                     "Czecho-wool-akia",
  "democratic-people-s-republic-of-korea": "Demo-baa-tic Korea",
  "democratic-republic-of-the-congo":   "Demo-baa-tic Congo",
  "denmark":                            "Den-baa-rk",
  "djibouti":                           "Djibaa-uti",
  "dominica":                           "Domi-baa-ca",
  "dominican-republic":                 "Domi-baa-can Rep.",
  "ecuador":                            "Ewe-cuador",
  "egypt":                              "E-fleece-pt",
  "el-salvador":                        "El Salva-baa-r",
  "equatorial-guinea":                  "Equa-wool-al Guinea",
  "eritrea":                            "Eri-fleece-a",
  "estonia":                            "Esto-baa-nia",
  "eswatini":                           "Ewe-swatini",
  "ethiopia":                           "Ethio-fleece-a",
  "ethiopia-pdr":                       "Ethio-fleece PDR",
  "faroe-islands":                      "Faroe Wool-ands",
  "fiji":                               "Fleece-ji",
  "finland":                            "Finn-baa-nd",
  "france":                             "Fran-baa",
  "french-guiana":                      "French Ewe-iana",
  "french-polynesia":                   "French Poly-baa-sia",
  "gabon":                              "Ga-baa-n",
  "gambia":                             "Gam-baa",
  "georgia":                            "Geor-fleece-ia",
  "germany":                            "Ger-baa-ny",
  "ghana":                              "Gha-baa",
  "greece":                             "Gre-fleece",
  "grenada":                            "Gre-baa-da",
  "guadeloupe":                         "Guade-ewe-pe",
  "guatemala":                          "Guate-baa-la",
  "guinea":                             "Gui-baa-a",
  "guinea-bissau":                      "Guinea-Baa-sau",
  "guyana":                             "Guy-baa-na",
  "haiti":                              "Hay-ti baa",
  "honduras":                           "Hon-baa-uras",
  "hungary":                            "Hungry for wool",
  "iceland":                            "Ice-fleece-land",
  "india":                              "Ewe-ndia",
  "indonesia":                          "Indo-baa-sia",
  "iran-islamic-republic-of":           "I-baa-n",
  "iraq":                               "I-baa-q",
  "ireland":                            "Ire-baa-land",
  "israel":                             "Is-wool-el",
  "italy":                              "It-baa-ly",
  "jamaica":                            "Ja-baa-ca",
  "japan":                              "Ja-baa-n",
  "jordan":                             "Jor-baa-n",
  "kazakhstan":                         "Kazakh-baa-tan",
  "kenya":                              "Ken-baa",
  "kuwait":                             "Ku-wool-t",
  "kyrgyzstan":                         "Kyr-baa-zstan",
  "latvia":                             "Lat-baa-ia",
  "lebanon":                            "Leba-baa-n",
  "lesotho":                            "Le-wool-tho",
  "liberia":                            "Libe-fleece-ia",
  "libya":                              "Li-baa-a",
  "lithuania":                          "Lithu-baa-nia",
  "luxembourg":                         "Luxem-baa-g",
  "madagascar":                         "Madagas-baa-r",
  "malawi":                             "Mala-wool-i",
  "malaysia":                           "Mala-baa-sia",
  "mali":                               "Maa-li!",
  "malta":                              "Malt-ewe",
  "martinique":                         "Marti-baa-que",
  "mauritania":                         "Mauri-baa-nia",
  "mauritius":                          "Mauri-fleece-us",
  "mexico":                             "Mexi-baa",
  "mongolia":                           "Mong-wool-ia",
  "montenegro":                         "Montene-baa-o",
  "morocco":                            "Mor-wool-co",
  "mozambique":                         "Mozam-baa-que",
  "myanmar":                            "Myan-baa-r",
  "namibia":                            "Nami-baa",
  "nepal":                              "Ne-baa-l",
  "netherlands-kingdom-of-the":         "Nether-baa-ds",
  "new-caledonia":                      "New Cale-baa-nia",
  "new-zealand":                        "New Zea-baa-nd",
  "nicaragua":                          "Nica-baa-gua",
  "niger":                              "Ni-baa-r",
  "nigeria":                            "Nige-baa-ia",
  "north-macedonia":                    "North Mace-baa-ia",
  "norway":                             "Nor-baa-y",
  "oman":                               "O-baa-n",
  "pakistan":                           "Paki-baa-tan",
  "palestine":                          "Pales-fleece",
  "papua-new-guinea":                   "Papua New Gui-baa",
  "paraguay":                           "Para-baa-y",
  "peru":                               "Pe-baa-u",
  "philippines":                        "Phili-baa-nes",
  "poland":                             "Po-baa-nd",
  "portugal":                           "Portu-baa-l",
  "puerto-rico":                        "Puerto Ewe-co",
  "qatar":                              "Qa-baa-r",
  "republic-of-korea":                  "Ko-baa-a",
  "republic-of-moldova":                "Mol-baa-va",
  "reunion":                            "Re-ewe-nion",
  "romania":                            "Roma-baa-ia",
  "russian-federation":                 "Russ-baa-an Fed.",
  "rwanda":                             "Rwan-baa",
  "saint-kitts-and-nevis":              "Saint Baa-tts",
  "saint-lucia":                        "Saint Ewe-cia",
  "saint-vincent-and-the-grenadines":   "Saint Vin-baa-t",
  "sao-tome-and-principe":              "Sao Tome-baa",
  "saudi-arabia":                       "Saudi Ara-baa",
  "senegal":                            "Sene-baa-l",
  "serbia":                             "Ser-baa-ia",
  "serbia-and-montenegro":              "Ser-baa Montenegro",
  "sierra-leone":                       "Sierra Ewe-one",
  "slovakia":                           "Slova-baa-ia",
  "slovenia":                           "Slove-baa-ia",
  "somalia":                            "Soma-baa-ia",
  "south-africa":                       "South Afri-fleece-a",
  "south-sudan":                        "South Su-baa-n",
  "spain":                              "S-baa-in",
  "sri-lanka":                          "Sri Wool-ka",
  "sudan":                              "Su-baa-n",
  "sudan-former":                       "Su-baa-n (old)",
  "suriname":                           "Suri-baa-me",
  "sweden":                             "Swe-baa-n",
  "switzerland":                        "Switzer-baa-nd",
  "syrian-arab-republic":               "Syr-baa-n Arab Rep.",
  "tajikistan":                         "Tajiki-baa-tan",
  "thailand":                           "Thaa-land",
  "timor-leste":                        "Ti-wool-Leste",
  "togo":                               "To-baa-go",
  "trinidad-and-tobago":                "Trini-baa-d",
  "tunisia":                            "Tuni-baa-ia",
  "turkiye":                            "Turk-ewe-ye",
  "turkmenistan":                       "Turkme-baa-stan",
  "uganda":                             "U-baa-nda",
  "ukraine":                            "Uk-baa-ine",
  "united-arab-emirates":               "United Ara-baa Emirates",
  "united-kingdom-of-great-britain-and-northern-ireland": "United Wool-dom",
  "united-republic-of-tanzania":        "Tanza-baa-ia",
  "united-states-of-america":           "United Baa-tes",
  "uruguay":                            "Uru-baa-y",
  "ussr":                               "US-ewe-SR",
  "uzbekistan":                         "Uzbeki-baa-tan",
  "venezuela-bolivarian-republic-of":   "Venezu-baa-la",
  "yemen":                              "Ye-baa-n",
  "yugoslav-sfr":                       "Yugos-baa-v SFR",
  "zambia":                             "Zam-baa",
  "zimbabwe":                           "Zimba-baa-we",
};

const json = JSON.parse(readFileSync("public/sheep.json", "utf8"));

for (const country of json.countries) {
  const pun = PUNS[country.slug];
  if (pun) {
    country.pun = pun;
  }
}

writeFileSync("public/sheep.json", JSON.stringify(json, null, 2));
console.log("Done. Puns added to", json.countries.filter(c => c.pun).length, "countries.");
